[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hpc-templates"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11,<3.12"
license = "MIT"
dependencies = [
  "equinox",
  "ciclo"
]